# Generated by Django 6.0.1 on 2026-01-31 11:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgeedge",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Knowledge Edge",
                "verbose_name_plural": "Knowledge Edges",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgenode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Knowledge Node",
                "verbose_name_plural": "Knowledge Nodes",
            },
        ),
        migrations.AddField(
            model_name="knowledgeedge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="엣지 생성 시각",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="knowledgeedge",
            name="is_prerequisite",
            field=models.BooleanField(
                db_index=True, default=False, help_text="선행조건 여부 (빠른 필터링용)"
            ),
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="cluster_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="클러스터링 알고리즘에 의해 할당된 클러스터 ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="노드 생성 시각",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="embedding",
            field=models.BinaryField(
                blank=True,
                help_text="벡터 임베딩 (numpy array를 pickle/bytes로 저장)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="confidence",
            field=models.FloatField(default=1.0, help_text="관계의 신뢰도 (0.0 ~ 1.0)"),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="엣지의 고유 식별자 (UUID)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("prerequisite", "Prerequisite"),
                    ("related", "Related"),
                    ("includes", "Includes"),
                    ("extends", "Extends"),
                    ("part_of", "Part Of"),
                    ("similar_to", "Similar To"),
                    ("contrast", "Contrast"),
                    ("causes", "Causes"),
                    ("implements", "Implements"),
                    ("derived_from", "Derived From"),
                ],
                db_index=True,
                help_text="관계 유형",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="source",
            field=models.ForeignKey(
                help_text="엣지의 시작 노드",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="out_edges",
                to="knowledge.knowledgenode",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="target",
            field=models.ForeignKey(
                help_text="엣지의 끝 노드",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_edges",
                to="knowledge.knowledgenode",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="노드에 대한 상세 설명"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="노드의 고유 식별자 (UUID)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="노드 태그 리스트 예: ['ml', 'optimization']",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="title",
            field=models.CharField(
                help_text="노드의 제목 (유일해야 함)", max_length=255, unique=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeedge",
            unique_together={("source", "target", "relation_type")},
        ),
        migrations.AddIndex(
            model_name="knowledgeedge",
            index=models.Index(
                fields=["source", "target"], name="knowledge_k_source__a05794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeedge",
            index=models.Index(
                fields=["relation_type"], name="knowledge_k_relatio_9c80b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeedge",
            index=models.Index(
                fields=["is_prerequisite"], name="knowledge_k_is_prer_2da0b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgenode",
            index=models.Index(fields=["title"], name="knowledge_k_title_116cbc_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgenode",
            index=models.Index(
                fields=["cluster_id"], name="knowledge_k_cluster_1b6976_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgenode",
            index=models.Index(
                fields=["created_at"], name="knowledge_k_created_08fbe7_idx"
            ),
        ),
    ]
