# Generated by Django 6.0.1 on 2026-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_alter_knowledgeedge_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgenode",
            name="x",
            field=models.FloatField(
                blank=True, help_text="3D 시각화 X 좌표", null=True
            ),
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="y",
            field=models.FloatField(
                blank=True, help_text="3D 시각화 Y 좌표", null=True
            ),
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="z",
            field=models.FloatField(
                blank=True, help_text="3D 시각화 Z 좌표", null=True
            ),
        ),
    ]
