# Generated by Django 6.0.1 on 2026-02-01 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_add_xyz_coordinates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgeedge",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "지식 엣지",
                "verbose_name_plural": "지식 엣지 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgenode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "지식 노드",
                "verbose_name_plural": "지식 노드 목록",
            },
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="difficulty_index",
            field=models.FloatField(
                default=0.5,
                help_text="D: 평균 인지 난이도 (0.0~1.0, 높을수록 어려움, 기본값 0.5)",
                verbose_name="인지 난이도",
            ),
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="stability_index",
            field=models.FloatField(
                default=0.5,
                help_text="S: 평균 기억 안정성 (유지 기간, 0.0~1.0, 기본값 0.5)",
                verbose_name="기억 안정성",
            ),
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="track_type",
            field=models.CharField(
                choices=[
                    ("TRACK_A", "Track A: 기존 도메인"),
                    ("TRACK_B", "Track B: 신규 도메인"),
                ],
                default="TRACK_A",
                help_text="A: 기존 도메인, B: 신규 도메인",
                max_length=10,
                verbose_name="트랙 유형",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="confidence",
            field=models.FloatField(
                default=1.0,
                help_text="관계의 신뢰도 (0.0 ~ 1.0)",
                verbose_name="신뢰도",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="엣지 생성 시각", verbose_name="생성 시각"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="id",
            field=models.BigAutoField(
                help_text="엣지의 고유 식별자",
                primary_key=True,
                serialize=False,
                verbose_name="엣지 ID",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="is_prerequisite",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="선행조건 여부 (빠른 필터링용)",
                verbose_name="선행조건 여부",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("prerequisite", "선행 조건"),
                    ("related", "관련됨"),
                    ("part_of", "일부"),
                    ("includes", "포함"),
                    ("extends", "확장"),
                    ("similar_to", "유사함"),
                    ("contrast", "대조"),
                    ("causes", "야기함"),
                    ("implements", "구현"),
                    ("derived_from", "파생"),
                ],
                db_index=True,
                default="related",
                help_text="prerequisite, related, part_of 등",
                max_length=50,
                verbose_name="관계 유형",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="source",
            field=models.ForeignKey(
                help_text="엣지의 시작 노드 (source → target)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="out_edges",
                to="knowledge.knowledgenode",
                verbose_name="시작 노드",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeedge",
            name="target",
            field=models.ForeignKey(
                help_text="엣지의 끝 노드 (source → target)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_edges",
                to="knowledge.knowledgenode",
                verbose_name="끝 노드",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="cluster_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="클러스터링 알고리즘에 의해 할당된 클러스터 ID",
                max_length=100,
                null=True,
                verbose_name="클러스터 ID",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="노드 생성 시각", verbose_name="생성 시각"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="노드에 대한 상세 설명",
                verbose_name="설명",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="embedding",
            field=models.BinaryField(
                blank=True,
                help_text="벡터 임베딩 (numpy array를 pickle/bytes로 저장)",
                null=True,
                verbose_name="임베딩 벡터",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="노드의 고유 식별자 (UUID)",
                primary_key=True,
                serialize=False,
                verbose_name="노드 ID",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="노드 태그 리스트 예: ['ml', 'optimization']",
                verbose_name="태그",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="title",
            field=models.CharField(
                help_text="노드의 제목 (유일해야 함)",
                max_length=255,
                unique=True,
                verbose_name="제목",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="x",
            field=models.FloatField(
                blank=True,
                help_text="3D 시각화 X 좌표",
                null=True,
                verbose_name="X 좌표",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="y",
            field=models.FloatField(
                blank=True,
                help_text="3D 시각화 Y 좌표",
                null=True,
                verbose_name="Y 좌표",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgenode",
            name="z",
            field=models.FloatField(
                blank=True,
                help_text="3D 시각화 Z 좌표",
                null=True,
                verbose_name="Z 좌표",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgenode",
            index=models.Index(
                fields=["track_type"], name="knowledge_k_track_t_8f4953_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeedge",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="no_self_loop",
            ),
        ),
    ]
