# Generated by Django 6.0.1 on 2026-02-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_alter_knowledgeedge_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="문제 내용")),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="4개의 문자열 보기 리스트",
                        verbose_name="보기 목록",
                    ),
                ),
                (
                    "answer_index",
                    models.IntegerField(
                        help_text="0 ~ 3 사이의 정수", verbose_name="정답 인덱스"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, default="", verbose_name="해설"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="knowledge.knowledgenode",
                        verbose_name="관련 지식 노드",
                    ),
                ),
            ],
            options={
                "verbose_name": "지식 퀴즈",
                "verbose_name_plural": "지식 퀴즈 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
