# Generated by Django 5.2.10 on 2026-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_knowledgequiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCluster",
            fields=[
                (
                    "cluster_id",
                    models.CharField(
                        help_text="클러스터 고유 식별자",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="클러스터 ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="LLM이 생성한 클러스터 이름",
                        max_length=255,
                        verbose_name="클러스터 이름",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="클러스터의 핵심 키워드 리스트",
                        verbose_name="핵심 키워드",
                    ),
                ),
                (
                    "node_count",
                    models.IntegerField(
                        default=0, help_text="클러스터에 속한 노드 개수", verbose_name="노드 수"
                    ),
                ),
                (
                    "is_named",
                    models.BooleanField(
                        default=False,
                        help_text="LLM에 의해 이름이 생성되었는지 여부",
                        verbose_name="이름 생성 완료",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
            ],
            options={
                "verbose_name": "지식 클러스터",
                "verbose_name_plural": "지식 클러스터 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
