"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# .env 파일 로드
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS 설정
ALLOWED_HOSTS = [
    "15.164.92.26",
    "3.37.88.166",  # 이전 IP (혹시 모르니 유지)
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 우리가 만든 앱 추가
    'knowledge',
    'analytics',
    'debug',  # 디버깅 API
    
    # 향후 API 개발을 위해 미리 추가
    'rest_framework',
    'corsheaders',
    
    # API 문서화
    'drf_spectacular',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# Django REST Framework 설정
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    # Swagger 문서화
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# =============================================================================
# drf-spectacular (Swagger/OpenAPI) 설정
# =============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'Memorylary API',
    'DESCRIPTION': '''
## 🧠 인지과학 기반 학습 시스템 API

Memorylary는 에빙하우스 망각곡선을 기반으로 개인화된 복습 스케줄을 제공하는 학습 시스템입니다.

### 주요 기능
- **Knowledge Graph**: 지식 노드 추출 및 관계 분석
- **Cognitive Benchmark**: 사용자 망각 계수 측정
- **Review Scheduling**: 최적 복습 시점 계산

### API 그룹
- `/api/v1/knowledge/` - 지식 그래프 관리
- `/api/v1/analytics/` - 인지 벤치마크 분석
- `/api/v1/universe/` - 3D 시각화 데이터
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Knowledge', 'description': '지식 그래프 생성 및 조회'},
        {'name': 'Analytics', 'description': '인지 벤치마크 및 분석'},
        {'name': 'Universe', 'description': '3D 시각화 데이터'},
        {'name': 'Tasks', 'description': '비동기 작업 상태'},
        {'name': 'Debug', 'description': '개발/테스트용 디버깅 API (⚠️ 프로덕션 비활성화 권장)'},
    ],
}


# =============================================================================
# Web Push (VAPID) 설정
# =============================================================================

# VAPID 키 (서버 식별 및 보안)
# 실제 프로덕션 환경에서는 반드시 .env 파일에 유효한 키를 설정해야 합니다.
# 생성 방법: python scripts/generate_vapid_keys.py (추후 제공)
VAPID_PUBLIC_KEY = os.getenv('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.getenv('VAPID_PRIVATE_KEY', '')
VAPID_ADMIN_EMAIL = os.getenv('VAPID_ADMIN_EMAIL', 'mailto:admin@example.com')


# =============================================================================
# Celery 설정
# =============================================================================

import os

# Redis 브로커 URL (환경 변수 또는 기본값)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Celery 태스크 설정
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30분 타임아웃


# =============================================================================
# CORS 설정 (프론트엔드 연동용)
# =============================================================================

CORS_ALLOW_ALL_ORIGINS = True  # 개발 환경용 (프로덕션에서는 제한 필요)
