# Generated by Django 6.0.1 on 2026-02-01 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0004_alter_knowledgeedge_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="테스트 결과 고유 식별자",
                        primary_key=True,
                        serialize=False,
                        verbose_name="결과 ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="A: 정답 여부 (True=1, False=0)",
                        verbose_name="정답 여부",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="C: 주관적 확신도 (0.0 ~ 1.0)", verbose_name="확신도"
                    ),
                ),
                (
                    "illusion_score",
                    models.FloatField(
                        blank=True,
                        help_text="C - A: 메타인지 착각 지수 (자동 계산됨)",
                        null=True,
                        verbose_name="착각 지수",
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        help_text="RT: 인출 반응 시간 (밀리초)",
                        verbose_name="반응 시간",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("A1_BOTTOM_UP", "A1: 상향식 (개념→정의)"),
                            ("A2_TOP_DOWN", "A2: 하향식 (정의→설명)"),
                            ("B_RECALL", "B: 자유 회상"),
                        ],
                        help_text="A1: 상향식, A2: 하향식(설명), B: 자유회상",
                        max_length=20,
                        verbose_name="테스트 유형",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        help_text="테스트 대상 지식 노드",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="knowledge.knowledgenode",
                        verbose_name="지식 노드",
                    ),
                ),
            ],
            options={
                "verbose_name": "테스트 결과",
                "verbose_name_plural": "테스트 결과 목록",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="테스트 세션 고유 식별자 (UUID)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="세션 ID",
                    ),
                ),
                (
                    "time_point",
                    models.CharField(
                        choices=[
                            ("T0", "직후 (0분)"),
                            ("T1", "20분 후"),
                            ("T2", "4시간 후"),
                            ("T3", "24시간 후"),
                        ],
                        default="T0",
                        help_text="망각 곡선 기반 측정 시점 (T0: 직후, T1: 20분, T2: 4시간, T3: 24시간)",
                        max_length=10,
                        verbose_name="측정 시점",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="테스트 예정 시각",
                        null=True,
                        verbose_name="예정 시각",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="테스트 실제 수행 시각",
                        null=True,
                        verbose_name="수행 시각",
                    ),
                ),
            ],
            options={
                "verbose_name": "테스트 세션",
                "verbose_name_plural": "테스트 세션 목록",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeechAnalysis",
            fields=[
                (
                    "result",
                    models.OneToOneField(
                        help_text="연결된 테스트 결과 (1:1 관계, A2 유형만)",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="speech_analysis",
                        serialize=False,
                        to="analytics.testresult",
                        verbose_name="테스트 결과",
                    ),
                ),
                (
                    "pause_count",
                    models.IntegerField(
                        default=0,
                        help_text="500ms 이상 침묵 구간 수 (인출 어려움 지표)",
                        verbose_name="침묵 구간 수",
                    ),
                ),
                (
                    "total_pause_duration",
                    models.IntegerField(
                        default=0,
                        help_text="총 침묵 시간 (밀리초)",
                        verbose_name="총 침묵 시간",
                    ),
                ),
                (
                    "speech_segments",
                    models.IntegerField(
                        default=0,
                        help_text="발화 마디 수 (설명 세분화 정도)",
                        verbose_name="발화 마디 수",
                    ),
                ),
                (
                    "text_length",
                    models.IntegerField(
                        default=0,
                        help_text="응답 텍스트 길이 (문자 수)",
                        verbose_name="텍스트 길이",
                    ),
                ),
            ],
            options={
                "verbose_name": "발화 분석",
                "verbose_name_plural": "발화 분석 목록",
            },
        ),
        migrations.AddField(
            model_name="testresult",
            name="session",
            field=models.ForeignKey(
                help_text="이 결과가 속한 테스트 세션",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="analytics.testsession",
                verbose_name="테스트 세션",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="사용자 고유 식별자 (UUID)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="사용자 ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="로그인에 사용되는 고유 사용자명",
                        max_length=150,
                        unique=True,
                        verbose_name="사용자명",
                    ),
                ),
                (
                    "alpha_user",
                    models.FloatField(
                        default=1.0,
                        help_text="개인별 학습 지능 계수 α (RT + 정답률 기반, 기본값 1.0)",
                        verbose_name="학습 지능 계수",
                    ),
                ),
                (
                    "base_forgetting_k",
                    models.FloatField(
                        default=0.5,
                        help_text="기초 망각 상수 k (초기 벤치마크 테스트 기반, 기본값 0.5)",
                        verbose_name="기초 망각 상수",
                    ),
                ),
                (
                    "illusion_avg",
                    models.FloatField(
                        default=0.0,
                        help_text="평균 메타인지 착각 성향 (양수: 과신, 음수: 신중, 기본값 0.0)",
                        verbose_name="평균 메타인지 착각",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="사용자 계정 생성 시각",
                        verbose_name="생성 시각",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["username"], name="analytics_u_usernam_ddd2c0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_u_created_456ba2_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="testsession",
            name="user",
            field=models.ForeignKey(
                help_text="테스트를 수행하는 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_sessions",
                to="analytics.user",
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["session", "node"], name="analytics_t_session_cb7b5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["test_type"], name="analytics_t_test_ty_9f4795_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["is_correct"], name="analytics_t_is_corr_9bccbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testsession",
            index=models.Index(
                fields=["user", "time_point"], name="analytics_t_user_id_917897_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testsession",
            index=models.Index(
                fields=["scheduled_at"], name="analytics_t_schedul_de1527_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testsession",
            index=models.Index(
                fields=["performed_at"], name="analytics_t_perform_f69fb0_idx"
            ),
        ),
    ]
