# Generated by Django 6.0.1 on 2026-02-03 06:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("knowledge", "0004_alter_knowledgeedge_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="스케줄 ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        default="all",
                        help_text="cs, dialect, 또는 all",
                        max_length=20,
                        verbose_name="도메인",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="복습 예정 시각", verbose_name="예정 시각"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="알림이 전송된 시각",
                        null=True,
                        verbose_name="알림 시각",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시각"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("NOTIFIED", "알림 전송됨"),
                            ("COMPLETED", "완료"),
                            ("SKIPPED", "건너뜀"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "target_retention",
                    models.FloatField(
                        default=0.8, help_text="0.0 ~ 1.0", verbose_name="목표 암기율"
                    ),
                ),
                (
                    "forgetting_k",
                    models.FloatField(
                        blank=True,
                        help_text="이 스케줄 계산에 사용된 k값",
                        null=True,
                        verbose_name="망각 계수",
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(default=False, verbose_name="수동 설정 여부"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        help_text="특정 노드에 대한 복습 (null이면 전체 도메인)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_schedules",
                        to="knowledge.knowledgenode",
                        verbose_name="복습 대상 노드",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_schedules",
                        to="analytics.user",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "복습 스케줄",
                "verbose_name_plural": "복습 스케줄 목록",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        default="macos",
                        help_text="macos, web_push, email 등",
                        max_length=50,
                        verbose_name="알림 유형",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="analytics.reviewschedule",
                        verbose_name="관련 스케줄",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 로그",
                "verbose_name_plural": "알림 로그 목록",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "endpoint",
                    models.URLField(max_length=500, verbose_name="엔드포인트"),
                ),
                ("p256dh", models.CharField(max_length=255, verbose_name="P256DH 키")),
                ("auth", models.CharField(max_length=255, verbose_name="Auth 키")),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="브라우저 정보",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="analytics.user",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Push 구독",
                "verbose_name_plural": "Web Push 구독 목록",
                "indexes": [
                    models.Index(
                        fields=["user", "last_used_at"],
                        name="analytics_p_user_id_5fda0a_idx",
                    )
                ],
                "unique_together": {("user", "endpoint")},
            },
        ),
        migrations.AddIndex(
            model_name="reviewschedule",
            index=models.Index(
                fields=["user", "status"], name="analytics_r_user_id_90e831_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewschedule",
            index=models.Index(
                fields=["scheduled_at"], name="analytics_r_schedul_e35004_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewschedule",
            index=models.Index(
                fields=["status", "scheduled_at"], name="analytics_r_status_a5f17e_idx"
            ),
        ),
    ]
