# Generated by Django 5.2.11 on 2026-02-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_schedule_models_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDomainStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="도메인 식별자 (cs, dialect 등)",
                        max_length=50,
                        verbose_name="도메인",
                    ),
                ),
                (
                    "alpha",
                    models.FloatField(
                        default=1.0,
                        help_text="해당 도메인의 학습 지능 계수",
                        verbose_name="학습 지능 계수",
                    ),
                ),
                (
                    "forgetting_k",
                    models.FloatField(
                        default=0.5, help_text="해당 도메인의 망각 상수", verbose_name="망각 상수"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_stats",
                        to="analytics.user",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "도메인별 통계",
                "verbose_name_plural": "도메인별 통계 목록",
                "indexes": [
                    models.Index(
                        fields=["user", "domain"], name="analytics_u_user_id_65e82a_idx"
                    )
                ],
                "unique_together": {("user", "domain")},
            },
        ),
    ]
