# Generated by Django 6.0.1 on 2026-02-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_userdomainstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdomainstat",
            name="illusion",
            field=models.FloatField(
                default=0.0,
                help_text="양수면 과신, 음수면 불신 (M)",
                verbose_name="메타인지 착각 계수",
            ),
        ),
    ]
